# Generated by Django 3.2.16 on 2025-04-07 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_group'),
        ('posts', '0004_post_group_alter_follow_user'),
        ('posts', '0035_remove_follow_unique_user_following'),
    ]

    operations = [
    ]
